#############################
### ENVIRONMENT VARIABLES ###
#############################


# See https://wiki.hyprland.org/Configuring/Environment-variables/

# Mouse Cursor Variables
env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24

# GDK Variables
env = GDK_BACKEND,wayland,x11,*
env = GDK_SCALE,1

# QT Variables
env = QT_QPA_PLATFORM,wayland;xcb
env = QT_AUTO_SCREEN_SCALE_FACTOR,1
env = QT_QPA_PLATFORMTHEME,qt5ct
env = QT_QPA_PLATFORMTHEME,qt6ct

# XDG Variables
env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_TYPE,wayland
env = XDG_SESSION_DESKTOP,Hyprland

# Other Variables
